// Hidden (non-sample) test cases for every seeded problem.
// Generated with verified reference solutions — do not edit expected values by hand.
export const hiddenTests: Record<string, { input: string; expectedOutput: string }[]> = {
  "two-sum": [
    { input: "[3,3], 6", expectedOutput: "[0,1]" },
    { input: "[1,2,3,4,5], 9", expectedOutput: "[3,4]" },
    { input: "[0,4,3,0], 0", expectedOutput: "[0,3]" },
    { input: "[-1,-2,-3,-4,-5], -8", expectedOutput: "[2,4]" },
    { input: "[1000000000,-1000000000,7,2], 9", expectedOutput: "[2,3]" },
    { input: "[5,75,25], 100", expectedOutput: "[1,2]" },
    { input: "[2,7,11,15], 26", expectedOutput: "[2,3]" },
    { input: "[10,20,30,40,50,60,70], 130", expectedOutput: "[5,6]" },
    { input: "[8,7,2,5,3,1], 11", expectedOutput: "[0,4]" },
    { input: "[4,4,9,1], 8", expectedOutput: "[0,1]" },
    { input: "[-3,4,3,90], 0", expectedOutput: "[0,2]" },
    { input: "[1,5], 6", expectedOutput: "[0,1]" },
  ],
  "sum-of-n-numbers": [
    { input: "1", expectedOutput: "1" },
    { input: "2", expectedOutput: "3" },
    { input: "3", expectedOutput: "6" },
    { input: "7", expectedOutput: "28" },
    { input: "50", expectedOutput: "1275" },
    { input: "100", expectedOutput: "5050" },
    { input: "999", expectedOutput: "499500" },
    { input: "1234", expectedOutput: "761995" },
    { input: "99999", expectedOutput: "4999950000" },
    { input: "100000", expectedOutput: "5000050000" },
  ],
  "valid-palindrome": [
    { input: "\"a\"", expectedOutput: "true" },
    { input: "\"ab\"", expectedOutput: "false" },
    { input: "\"aa\"", expectedOutput: "true" },
    { input: "\"0P\"", expectedOutput: "false" },
    { input: "\"Was it a car or a cat I saw?\"", expectedOutput: "true" },
    { input: "\"No lemon, no melon\"", expectedOutput: "true" },
    { input: "\"hello world\"", expectedOutput: "false" },
    { input: "\"12321\"", expectedOutput: "true" },
    { input: "\"1a2\"", expectedOutput: "false" },
    { input: "\"Able was I ere I saw Elba\"", expectedOutput: "true" },
    { input: "\"not a palindrome at all\"", expectedOutput: "false" },
    { input: "\"...,,,\"", expectedOutput: "true" },
  ],
  "reverse-string": [
    { input: "\"a\"", expectedOutput: "\"a\"" },
    { input: "\"ab\"", expectedOutput: "\"ba\"" },
    { input: "\"racecar\"", expectedOutput: "\"racecar\"" },
    { input: "\"OpenJudge2026\"", expectedOutput: "\"6202egduJnepO\"" },
    { input: "\"a b c\"", expectedOutput: "\"c b a\"" },
    { input: "\"12345\"", expectedOutput: "\"54321\"" },
    { input: "\"The quick brown fox\"", expectedOutput: "\"xof nworb kciuq ehT\"" },
    { input: "\"zzzzzz\"", expectedOutput: "\"zzzzzz\"" },
    { input: "\"Palindrome-emordnilaP\"", expectedOutput: "\"Palindrome-emordnilaP\"" },
    { input: "\"x\"", expectedOutput: "\"x\"" },
  ],
  "fibonacci-number": [
    { input: "0", expectedOutput: "0" },
    { input: "1", expectedOutput: "1" },
    { input: "2", expectedOutput: "1" },
    { input: "3", expectedOutput: "2" },
    { input: "5", expectedOutput: "5" },
    { input: "12", expectedOutput: "144" },
    { input: "20", expectedOutput: "6765" },
    { input: "30", expectedOutput: "832040" },
    { input: "40", expectedOutput: "102334155" },
    { input: "45", expectedOutput: "1134903170" },
  ],
  "valid-parentheses": [
    { input: "\"(\"", expectedOutput: "false" },
    { input: "\")\"", expectedOutput: "false" },
    { input: "\"()\"", expectedOutput: "true" },
    { input: "\"(((\"", expectedOutput: "false" },
    { input: "\"()()()\"", expectedOutput: "true" },
    { input: "\"({[]})\"", expectedOutput: "true" },
    { input: "\"([)]\"", expectedOutput: "false" },
    { input: "\"{[]}\"", expectedOutput: "true" },
    { input: "\"((()))\"", expectedOutput: "true" },
    { input: "\"(){}[]{()}\"", expectedOutput: "true" },
    { input: "\"]\"", expectedOutput: "false" },
  ],
  "binary-search": [
    { input: "[1], 1", expectedOutput: "0" },
    { input: "[1], 0", expectedOutput: "-1" },
    { input: "[1,3], 3", expectedOutput: "1" },
    { input: "[-100,-50,0,50,100], -100", expectedOutput: "0" },
    { input: "[-100,-50,0,50,100], 100", expectedOutput: "4" },
    { input: "[-100,-50,0,50,100], 25", expectedOutput: "-1" },
    { input: "[2,4,6,8,10,12,14,16], 2", expectedOutput: "0" },
    { input: "[2,4,6,8,10,12,14,16], 16", expectedOutput: "7" },
    { input: "[1,2,3,4,5,6,7,8,9,10], 7", expectedOutput: "6" },
    { input: "[5,10,15,20,25], 26", expectedOutput: "-1" },
  ],
  "maximum-subarray": [
    { input: "[1]", expectedOutput: "1" },
    { input: "[-1]", expectedOutput: "-1" },
    { input: "[-2,-1,-3]", expectedOutput: "-1" },
    { input: "[1,2,3,4,5]", expectedOutput: "15" },
    { input: "[-1,0,-2]", expectedOutput: "0" },
    { input: "[8,-19,5,-4,20]", expectedOutput: "21" },
    { input: "[1,-1,1,-1,1]", expectedOutput: "1" },
    { input: "[100,-1,100]", expectedOutput: "199" },
    { input: "[0,0,0,0]", expectedOutput: "0" },
    { input: "[-5,8,-6,12,-30,7]", expectedOutput: "14" },
  ],
  "longest-substring-without-repeating-characters": [
    { input: "\"\"", expectedOutput: "0" },
    { input: "\"a\"", expectedOutput: "1" },
    { input: "\"au\"", expectedOutput: "2" },
    { input: "\"aab\"", expectedOutput: "2" },
    { input: "\"dvdf\"", expectedOutput: "3" },
    { input: "\"pwwkew\"", expectedOutput: "3" },
    { input: "\"abcdefg\"", expectedOutput: "7" },
    { input: "\"aaaaaaa\"", expectedOutput: "1" },
    { input: "\"abba\"", expectedOutput: "2" },
    { input: "\"tmmzuxt\"", expectedOutput: "5" },
    { input: "\"abcabcabcd\"", expectedOutput: "4" },
  ],
  "climbing-stairs": [
    { input: "1", expectedOutput: "1" },
    { input: "3", expectedOutput: "3" },
    { input: "4", expectedOutput: "5" },
    { input: "6", expectedOutput: "13" },
    { input: "10", expectedOutput: "89" },
    { input: "15", expectedOutput: "987" },
    { input: "20", expectedOutput: "10946" },
    { input: "30", expectedOutput: "1346269" },
    { input: "44", expectedOutput: "1134903170" },
    { input: "45", expectedOutput: "1836311903" },
  ],
  "contains-duplicate": [
    { input: "[1]", expectedOutput: "false" },
    { input: "[1,1]", expectedOutput: "true" },
    { input: "[1,2]", expectedOutput: "false" },
    { input: "[0,0,0]", expectedOutput: "true" },
    { input: "[1000000000,-1000000000]", expectedOutput: "false" },
    { input: "[3,1,4,1,5]", expectedOutput: "true" },
    { input: "[9,8,7,6,5,4,3,2,1]", expectedOutput: "false" },
    { input: "[2,2]", expectedOutput: "true" },
    { input: "[10,20,30,40,10]", expectedOutput: "true" },
    { input: "[7,3,7]", expectedOutput: "true" },
  ],
  "best-time-to-buy-and-sell-stock": [
    { input: "[5]", expectedOutput: "0" },
    { input: "[1,2]", expectedOutput: "1" },
    { input: "[2,1]", expectedOutput: "0" },
    { input: "[3,3,3,3]", expectedOutput: "0" },
    { input: "[1,2,3,4,5,6]", expectedOutput: "5" },
    { input: "[6,5,4,3,2,1]", expectedOutput: "0" },
    { input: "[2,4,1,7]", expectedOutput: "6" },
    { input: "[10,1,10,1,10]", expectedOutput: "9" },
    { input: "[0,10000]", expectedOutput: "10000" },
    { input: "[5,11,3,50,60,90]", expectedOutput: "87" },
  ],
  "missing-number": [
    { input: "[0]", expectedOutput: "1" },
    { input: "[1]", expectedOutput: "0" },
    { input: "[1,0]", expectedOutput: "2" },
    { input: "[2,0]", expectedOutput: "1" },
    { input: "[0,1,2,3,4,5,6,7,9]", expectedOutput: "8" },
    { input: "[5,4,3,2,1,0]", expectedOutput: "6" },
    { input: "[1,2,3,4,5,6,7,8,9,10]", expectedOutput: "0" },
    { input: "[0,2]", expectedOutput: "1" },
    { input: "[4,2,1,0]", expectedOutput: "3" },
    { input: "[9,6,4,2,3,5,7,0,8]", expectedOutput: "1" },
  ],
  "count-primes": [
    { input: "0", expectedOutput: "0" },
    { input: "1", expectedOutput: "0" },
    { input: "2", expectedOutput: "0" },
    { input: "3", expectedOutput: "1" },
    { input: "4", expectedOutput: "2" },
    { input: "11", expectedOutput: "4" },
    { input: "100", expectedOutput: "25" },
    { input: "1000", expectedOutput: "168" },
    { input: "49999", expectedOutput: "5132" },
    { input: "100000", expectedOutput: "9592" },
  ],
  "house-robber": [
    { input: "[0]", expectedOutput: "0" },
    { input: "[5]", expectedOutput: "5" },
    { input: "[1,2]", expectedOutput: "2" },
    { input: "[2,1,1,2]", expectedOutput: "4" },
    { input: "[0,0,0]", expectedOutput: "0" },
    { input: "[100]", expectedOutput: "100" },
    { input: "[1,3,1,3,100]", expectedOutput: "103" },
    { input: "[400,400,400]", expectedOutput: "800" },
    { input: "[5,1,2,10,6,2,7,9,3,1]", expectedOutput: "27" },
    { input: "[10,2,2,10]", expectedOutput: "20" },
  ],
  "container-with-most-water": [
    { input: "[1,1]", expectedOutput: "1" },
    { input: "[1,2,1]", expectedOutput: "2" },
    { input: "[4,3,2,1,4]", expectedOutput: "16" },
    { input: "[1,2,4,3]", expectedOutput: "4" },
    { input: "[10000,10000]", expectedOutput: "10000" },
    { input: "[1,8,6,2,5,4,8,3,7]", expectedOutput: "49" },
    { input: "[2,3,10,5,7,8,9]", expectedOutput: "36" },
    { input: "[0,0,0,5]", expectedOutput: "0" },
    { input: "[5,0,0,0,5]", expectedOutput: "20" },
    { input: "[3,9,3,4,7,2,12,6]", expectedOutput: "45" },
  ],
  "coin-change": [
    { input: "[1], 0", expectedOutput: "0" },
    { input: "[1], 1", expectedOutput: "1" },
    { input: "[1], 2", expectedOutput: "2" },
    { input: "[2], 3", expectedOutput: "-1" },
    { input: "[1,2,5], 100", expectedOutput: "20" },
    { input: "[5,10,25], 30", expectedOutput: "2" },
    { input: "[186,419,83,408], 6249", expectedOutput: "20" },
    { input: "[2,5,10,1], 27", expectedOutput: "4" },
    { input: "[3,7,405,436], 8839", expectedOutput: "25" },
    { input: "[7], 14", expectedOutput: "2" },
  ],
  "jump-game": [
    { input: "[0]", expectedOutput: "true" },
    { input: "[1]", expectedOutput: "true" },
    { input: "[0,1]", expectedOutput: "false" },
    { input: "[1,0]", expectedOutput: "true" },
    { input: "[2,0,0]", expectedOutput: "true" },
    { input: "[1,1,1,1]", expectedOutput: "true" },
    { input: "[4,0,0,0,0]", expectedOutput: "true" },
    { input: "[1,0,1,0]", expectedOutput: "false" },
    { input: "[5,4,3,2,1,0,0]", expectedOutput: "false" },
    { input: "[1,2,0,1,0,2,0,0,1]", expectedOutput: "false" },
    { input: "[10,0,0,0,0,0,0,0,0,0,1]", expectedOutput: "true" },
  ],
  "trapping-rain-water": [
    { input: "[1]", expectedOutput: "0" },
    { input: "[1,2]", expectedOutput: "0" },
    { input: "[2,1]", expectedOutput: "0" },
    { input: "[3,0,3]", expectedOutput: "3" },
    { input: "[0,0,0,0]", expectedOutput: "0" },
    { input: "[5,4,3,2,1]", expectedOutput: "0" },
    { input: "[1,2,3,4,5]", expectedOutput: "0" },
    { input: "[2,0,2,0,2,0,2]", expectedOutput: "6" },
    { input: "[6,1,4,0,6]", expectedOutput: "13" },
    { input: "[5,5,1,7,1,1,5,2,7,6]", expectedOutput: "23" },
  ],
  "first-missing-positive": [
    { input: "[1]", expectedOutput: "2" },
    { input: "[2]", expectedOutput: "1" },
    { input: "[-1]", expectedOutput: "1" },
    { input: "[1,1]", expectedOutput: "2" },
    { input: "[7,8,9,11,12]", expectedOutput: "1" },
    { input: "[1,2,3,4,5]", expectedOutput: "6" },
    { input: "[5,4,3,2,1]", expectedOutput: "6" },
    { input: "[0,-10,-20]", expectedOutput: "1" },
    { input: "[2,3,4,5,6,7]", expectedOutput: "1" },
    { input: "[1,3,5,7,9,2,4,6,8,10]", expectedOutput: "11" },
  ],
};
